"""
AI Excel Agent Demo
Requires:
    pip install "xlwings>=0.33.0"

Purpose:
- Demonstrates a safe architecture where an LLM produces a structured plan.
- Only whitelisted actions are executed.
- The script does NOT execute arbitrary Python generated by an LLM.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any, Callable
import json
import shutil

import xlwings as xw


ALLOWED_ACTIONS = {
    "sort_sales_by_date",
    "highlight_low_sales",
    "create_regional_report",
    "refresh_inventory_alerts",
    "highlight_project_risks",
    "create_backup",
    "refresh_dashboard",
}


@dataclass
class AgentContext:
    workbook_path: Path
    backup_path: Path | None = None


def last_used_row(sheet: xw.Sheet, column: str = "A") -> int:
    """Finds the last non-empty row in a column."""
    return sheet.range(f"{column}{sheet.cells.last_cell.row}").end("up").row


def create_backup(ctx: AgentContext) -> None:
    stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    backup_path = ctx.workbook_path.with_name(
        f"{ctx.workbook_path.stem}_backup_{stamp}{ctx.workbook_path.suffix}"
    )
    shutil.copy2(ctx.workbook_path, backup_path)
    ctx.backup_path = backup_path


def sort_sales_by_date(wb: xw.Book, params: dict[str, Any]) -> None:
    sht = wb.sheets["Sales_Data"]
    last_row = last_used_row(sht, "A")
    full_range = sht.range(f"A1:Q{last_row}")

    # Native Excel sort is used through the underlying COM/AppScript object.
    # Windows example:
    if xw.platform == "win32":
        full_range.api.Sort(
            Key1=sht.range("B2").api,
            Order1=1,  # xlAscending
            Header=1,  # xlYes
        )
    else:
        # On macOS, simple deterministic fallback: read, sort in Python, write back.
        values = sht.range(f"A2:Q{last_row}").value
        values.sort(key=lambda row: row[1] or datetime.min)
        sht.range(f"A2:Q{last_row}").value = values


def highlight_low_sales(wb: xw.Book, params: dict[str, Any]) -> None:
    threshold = float(params.get("threshold", 100_000))
    sht = wb.sheets["Sales_Data"]
    last_row = last_used_row(sht, "A")
    target = sht.range(f"L2:L{last_row}")

    # Clear existing conditional formats only in target range.
    target.api.FormatConditions.Delete()
    condition = target.api.FormatConditions.Add(
        Type=1,             # xlCellValue
        Operator=6,         # xlLess
        Formula1=str(threshold),
    )
    condition.Interior.Color = 13421823  # light red (Windows COM color integer)


def create_regional_report(wb: xw.Book, params: dict[str, Any]) -> None:
    source = wb.sheets["Sales_Data"]
    last_row = last_used_row(source, "A")
    values = source.range(f"A1:Q{last_row}").value
    headers = values[0]
    rows = values[1:]

    region_idx = headers.index("Region")
    sales_idx = headers.index("Sales")
    profit_idx = headers.index("Gross_Profit")

    grouped: dict[str, dict[str, float]] = {}
    for row in rows:
        region = row[region_idx]
        grouped.setdefault(region, {"Revenue": 0.0, "Gross_Profit": 0.0})
        grouped[region]["Revenue"] += float(row[sales_idx] or 0)
        grouped[region]["Gross_Profit"] += float(row[profit_idx] or 0)

    sheet_name = params.get("output_sheet", "Regional_Report")
    if sheet_name in [s.name for s in wb.sheets]:
        wb.sheets[sheet_name].delete()
    report = wb.sheets.add(sheet_name, after=wb.sheets[-1])

    output = [["Region", "Revenue", "Gross_Profit", "Profit_Margin"]]
    for region, metrics in sorted(grouped.items()):
        revenue = metrics["Revenue"]
        profit = metrics["Gross_Profit"]
        margin = profit / revenue if revenue else 0
        output.append([region, revenue, profit, margin])

    report.range("A1").value = output
    report.range("A1:D1").color = (68, 114, 196)
    report.range("A1:D1").font.color = (255, 255, 255)
    report.range("A1:D1").font.bold = True
    report.range(f"B2:C{len(output)}").number_format = '#,##0"원"'
    report.range(f"D2:D{len(output)}").number_format = "0.0%"
    report.autofit()

    chart = report.charts.add(
        left=report.range("F2").left,
        top=report.range("F2").top,
        width=560,
        height=320,
    )
    chart.set_source_data(report.range(f"A1:C{len(output)}"))
    chart.chart_type = "column_clustered"
    chart.name = "RegionalPerformanceChart"


def refresh_inventory_alerts(wb: xw.Book, params: dict[str, Any]) -> None:
    sht = wb.sheets["Inventory"]
    last_row = last_used_row(sht, "A")
    sht.range("H2").formula = '=IF(E2<=F2,"발주필요",IF(E2<=F2*1.5,"주의","정상"))'
    sht.range(f"H2:H{last_row}").fill_down()
    sht.range("I2").formula = "=MAX(0,F2*2-E2)"
    sht.range(f"I2:I{last_row}").fill_down()


def highlight_project_risks(wb: xw.Book, params: dict[str, Any]) -> None:
    days = int(params.get("days", 7))
    progress_limit = float(params.get("progress_limit", 0.8))
    sht = wb.sheets["Project_Plan"]
    last_row = last_used_row(sht, "A")
    rows = sht.range(f"A2:L{last_row}").value

    for offset, row in enumerate(rows, start=2):
        due_date = row[5]
        status = row[7]
        progress = float(row[8] or 0)
        if status != "완료" and due_date:
            remaining = (due_date.date() - datetime.now().date()).days
            if remaining <= days and progress < progress_limit:
                sht.range(f"A{offset}:L{offset}").color = (255, 242, 204)


def refresh_dashboard(wb: xw.Book, params: dict[str, Any]) -> None:
    """Recalculates formulas and refreshes charts/pivots/connections where Excel supports them."""
    wb.app.calculate()
    if xw.platform == "win32":
        wb.api.RefreshAll()


ACTION_HANDLERS: dict[str, Callable[[xw.Book, dict[str, Any]], None]] = {
    "sort_sales_by_date": sort_sales_by_date,
    "highlight_low_sales": highlight_low_sales,
    "create_regional_report": create_regional_report,
    "refresh_inventory_alerts": refresh_inventory_alerts,
    "highlight_project_risks": highlight_project_risks,
    "refresh_dashboard": refresh_dashboard,
}


def validate_plan(plan: dict[str, Any], wb: xw.Book) -> None:
    if not isinstance(plan.get("steps"), list) or not plan["steps"]:
        raise ValueError("Plan must contain at least one step.")

    existing_sheets = {s.name for s in wb.sheets}
    for idx, step in enumerate(plan["steps"], start=1):
        action = step.get("action")
        if action not in ALLOWED_ACTIONS:
            raise ValueError(f"Step {idx}: action is not allowed: {action}")

        target_sheet = step.get("params", {}).get("sheet")
        if target_sheet and target_sheet not in existing_sheets:
            raise ValueError(f"Step {idx}: sheet does not exist: {target_sheet}")


def execute_plan(workbook_path: str | Path, plan: dict[str, Any]) -> dict[str, Any]:
    path = Path(workbook_path).resolve()
    if not path.exists():
        raise FileNotFoundError(path)

    ctx = AgentContext(workbook_path=path)
    if plan.get("requires_backup", True):
        create_backup(ctx)

    log: dict[str, Any] = {
        "request_id": plan.get("request_id"),
        "workbook": str(path),
        "backup": str(ctx.backup_path) if ctx.backup_path else None,
        "started_at": datetime.now().isoformat(timespec="seconds"),
        "steps": [],
        "status": "running",
    }

    app = xw.App(visible=True, add_book=False)
    try:
        app.display_alerts = False
        app.screen_updating = False
        wb = app.books.open(str(path))
        validate_plan(plan, wb)

        for step in plan["steps"]:
            action = step["action"]
            params = step.get("params", {})
            if action == "create_backup":
                create_backup(ctx)
            else:
                ACTION_HANDLERS[action](wb, params)
            log["steps"].append({"action": action, "status": "success"})

        wb.save()
        log["status"] = "success"
        log["finished_at"] = datetime.now().isoformat(timespec="seconds")
        wb.close()
        return log

    except Exception as exc:
        log["status"] = "failed"
        log["error"] = repr(exc)
        log["finished_at"] = datetime.now().isoformat(timespec="seconds")
        # Original workbook can be restored from ctx.backup_path if necessary.
        raise
    finally:
        app.screen_updating = True
        app.display_alerts = True
        app.quit()


# In production, replace this rule-based function with an LLM call that returns
# the same JSON structure. Validate the response before execution.
def example_natural_language_to_plan(command: str) -> dict[str, Any]:
    normalized = command.replace(" ", "")

    if "지역별" in normalized and ("차트" in normalized or "집계" in normalized):
        steps = [{"action": "create_regional_report", "params": {"output_sheet": "Regional_Report"}}]
    elif "날짜" in normalized and "정렬" in normalized:
        steps = [{"action": "sort_sales_by_date", "params": {}}]
    elif "10만원미만" in normalized or "100000원미만" in normalized:
        steps = [{"action": "highlight_low_sales", "params": {"threshold": 100000}}]
    elif "재고" in normalized and ("발주" in normalized or "재주문" in normalized):
        steps = [{"action": "refresh_inventory_alerts", "params": {}}]
    elif "마감" in normalized and "진행률" in normalized:
        steps = [{"action": "highlight_project_risks", "params": {"days": 7, "progress_limit": 0.8}}]
    elif "대시보드" in normalized and ("갱신" in normalized or "업데이트" in normalized):
        steps = [{"action": "refresh_dashboard", "params": {}}]
    else:
        raise ValueError("This demo parser does not recognize the command.")

    return {
        "request_id": f"REQ-{datetime.now():%Y%m%d%H%M%S}",
        "requires_backup": True,
        "steps": steps,
    }


if __name__ == "__main__":
    workbook = Path(__file__).with_name("AI_Excel_Automation_Demo.xlsx")
    user_command = "지역별 매출과 이익을 집계해서 새 시트와 차트를 만들어줘."
    action_plan = example_natural_language_to_plan(user_command)
    print(json.dumps(action_plan, ensure_ascii=False, indent=2))
    result = execute_plan(workbook, action_plan)
    print(json.dumps(result, ensure_ascii=False, indent=2))
